-d C:\Users\freda\Documents\First_test_tang_nano_4k\impl\gwsynthesis\First_test_tang_nano_4k.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst C:\Users\freda\Documents\First_test_tang_nano_4k\src\board_physical.cst
-cfg C:\Users\freda\Documents\First_test_tang_nano_4k\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
